#!/usr/bin/python3
# -*- coding: UTF-8 -*-

#
# This program use to manage job. when you submit jobto server,
# the script will send a message to host that you set.
# 
# USAGE:
# ./toctc.py -n a -t 10:34 -p /home/liuhui -s 0
#

from socket import *
import optparse
import sys

def parseOption():
    """
    """
    usage = "usage: %prog [options] arg1 arg2"
    p = optparse.OptionParser(usage=usage)
    p.add_option('-n', '--name', action='store', dest='jobname')
    p.add_option('-t', '--time', action='store', dest='subtime')
    p.add_option('-s', '--status', action='store', type="int", dest='status')
    p.add_option('-p', '--path', action='store', dest='path')

    opt, args = p.parse_args()
    # convert opt from parser object to dict.
    opt = eval(str(opt))
    # Check the option value
    for key, value in opt.items():
        if value == None:
            p.print_help()
            sys.exit(1)
    return opt

def sendmessage(message, host='59.77.33.128', port=8888, code='utf-8'):
    """
    """
    host = '127.0.0.1'
    s = socket(AF_INET, SOCK_STREAM)
    s.connect((host, port))
    # encode and send Message
    s.send(cmd.encode(code))
    # receive message
    # tm = s.recv(1024)
    s.close()
    return True

if __name__ == '__main__':

 #  cmd = parseOption()
 #  print(cmd)
 #  sys.exit(0)
    #cmd = ['job01', '1', 'pauling']
    cmd = 'quit'
    cmd = str(cmd)

    if sendmessage(cmd):
        sys.exit(0)
    else:
        sys.exit(1)
